/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddFeedbackLabelDialog: typeof import('./src/components/label/AddFeedbackLabelDialog.vue')['default']
    AddProductLabelDialog: typeof import('./src/components/label/AddProductLabelDialog.vue')['default']
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    AppSidebar: typeof import('./src/components/layout/AppSidebar.vue')['default']
    BaseChart: typeof import('./src/components/charts/BaseChart.vue')['default']
    CopyUserDialog: typeof import('./src/components/account/CopyUserDialog.vue')['default']
    CreateUserDialog: typeof import('./src/components/account/CreateUserDialog.vue')['default']
    DimensionSelector: typeof import('./src/components/analysis/DimensionSelector.vue')['default']
    EditUserDialog: typeof import('./src/components/account/EditUserDialog.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ExportLabelDialog: typeof import('./src/components/label/ExportLabelDialog.vue')['default']
    FilterPanel: typeof import('./src/components/analysis/FilterPanel.vue')['default']
    FilterSelector: typeof import('./src/components/FilterSelector.vue')['default']
    ImportLabelDialog: typeof import('./src/components/label/ImportLabelDialog.vue')['default']
    LabelUsageDialog: typeof import('./src/components/label/LabelUsageDialog.vue')['default']
    MainLayout: typeof import('./src/components/layout/MainLayout.vue')['default']
    PermissionDialog: typeof import('./src/components/account/PermissionDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimpleFilterSelector: typeof import('./src/components/SimpleFilterSelector.vue')['default']
    UploadModal: typeof import('./src/components/datasource/UploadModal.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
