version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: chime_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: chime_dashboard
      MYSQL_USER: chime_user
      MYSQL_PASSWORD: chime_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - chime_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # FastAPI Backend
  backend:
    build: .
    container_name: chime_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql://root:123456@mysql:3306/chime_dashboard
      - SECRET_KEY=your-production-secret-key-here
      - LLM_API_URL=http://192.168.50.123:11434/api/generate
      - LLM_MODEL_NAME=qwen3:8b
      - HOST=0.0.0.0
      - PORT=8000
      - LOG_LEVEL=INFO
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
    networks:
      - chime_network
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mysql_data:

networks:
  chime_network:
    driver: bridge