"""Initial migration

Revision ID: 940f422d0a05
Revises: 
Create Date: 2025-07-25 22:00:45.657498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '940f422d0a05'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'OPERATOR', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('feedback_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_categories_is_active'), 'feedback_categories', ['is_active'], unique=False)
    op.create_index(op.f('ix_feedback_categories_name'), 'feedback_categories', ['name'], unique=True)
    op.create_table('product_labels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_labels_is_active'), 'product_labels', ['is_active'], unique=False)
    op.create_index(op.f('ix_product_labels_name'), 'product_labels', ['name'], unique=True)
    op.create_table('voice_files',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('file_format', sa.Enum('WAV', 'MP3', 'TXT', name='fileformat'), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='filestatus'), nullable=False),
    sa.Column('uploaded_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_files_created_at'), 'voice_files', ['created_at'], unique=False)
    op.create_index(op.f('ix_voice_files_status'), 'voice_files', ['status'], unique=False)
    op.create_index(op.f('ix_voice_files_uploaded_by'), 'voice_files', ['uploaded_by'], unique=False)
    op.create_table('voice_analysis',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('file_id', sa.String(length=50), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.Enum('POSITIVE', 'NEGATIVE', 'NEUTRAL', name='sentimenttype'), nullable=False),
    sa.Column('feedback_category', sa.String(length=100), nullable=True),
    sa.Column('feedback_summary', sa.String(length=100), nullable=True),
    sa.Column('product_names', sa.JSON(), nullable=True),
    sa.Column('analysis_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['voice_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_analysis_analysis_time'), 'voice_analysis', ['analysis_time'], unique=False)
    op.create_index(op.f('ix_voice_analysis_feedback_category'), 'voice_analysis', ['feedback_category'], unique=False)
    op.create_index(op.f('ix_voice_analysis_file_id'), 'voice_analysis', ['file_id'], unique=False)
    op.create_index(op.f('ix_voice_analysis_sentiment'), 'voice_analysis', ['sentiment'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voice_analysis_sentiment'), table_name='voice_analysis')
    op.drop_index(op.f('ix_voice_analysis_file_id'), table_name='voice_analysis')
    op.drop_index(op.f('ix_voice_analysis_feedback_category'), table_name='voice_analysis')
    op.drop_index(op.f('ix_voice_analysis_analysis_time'), table_name='voice_analysis')
    op.drop_table('voice_analysis')
    op.drop_index(op.f('ix_voice_files_uploaded_by'), table_name='voice_files')
    op.drop_index(op.f('ix_voice_files_status'), table_name='voice_files')
    op.drop_index(op.f('ix_voice_files_created_at'), table_name='voice_files')
    op.drop_table('voice_files')
    op.drop_index(op.f('ix_product_labels_name'), table_name='product_labels')
    op.drop_index(op.f('ix_product_labels_is_active'), table_name='product_labels')
    op.drop_table('product_labels')
    op.drop_index(op.f('ix_feedback_categories_name'), table_name='feedback_categories')
    op.drop_index(op.f('ix_feedback_categories_is_active'), table_name='feedback_categories')
    op.drop_table('feedback_categories')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###